In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Učitavanje skupa podataka

In [2]:
data = pd.read_csv('../podaci/psyco.csv')
datac = pd.read_csv('../podaci/psyco.csv')
data.head()

age  gender          occupation line_of_work  time_bp  time_dp   
0   19-25    Male  Student in College          NaN        7        5  \
1  Dec-18    Male   Student in School          NaN        7       11   
2   19-25    Male  Student in College          NaN        7        7   
3   19-25    Male  Student in College          NaN        7        7   
4   19-25  Female  Student in College          NaN        7        7   

   travel_time  easeof_online  home_env  prod_inc  ...  fam_connect  relaxed   
0          0.5              3         3       0.0  ...          1.0     -0.5  \
1          0.5              4         2      -0.5  ...          1.0      1.0   
2          1.5              2         2       1.0  ...          0.5      0.5   
3          1.5              3         1       0.0  ...          0.0     -1.0   
4          1.5              2         2       0.0  ...          0.0      0.5   

   self_time  like_hw  dislike_hw                        prefer   
0       -0.5      100           1  Complete Physical Attendance  \
1        1.0     1111        1110  Complete Physical Attendance   
2        0.5     1100         111  Complete Physical Attendance   
3       -0.5      100        1111  Complete Physical Attendance   
4        0.0     1010        1000  Complete Physical Attendance   

   certaindays_hw Unnamed: 19 time_bp.1  travel+work  
0             Yes         NaN         7          NaN  
1              No         NaN         7          NaN  
2             Yes         NaN         7          NaN  
3             Yes         NaN         7          NaN  
4             Yes         NaN         7          NaN  

[5 rows x 22 columns]

### Uklanjanje grešaka

In [3]:
data["age"].unique()

array(['19-25', 'Dec-18', '33-40', '60+', '26-32', '40-50', '50-60'],
      dtype=object)

Primećujemo da postoji greška među podacima u koloni 'age' - potrebno je vrednost 'Dec-18' zameniti sa '0-18'.

In [4]:
data['age'].replace('Dec-18', '0-18', inplace = True)
data["age"].unique()

array(['19-25', '0-18', '33-40', '60+', '26-32', '40-50', '50-60'],
      dtype=object)

In [5]:
data.head()

age  gender          occupation line_of_work  time_bp  time_dp   
0  19-25    Male  Student in College          NaN        7        5  \
1   0-18    Male   Student in School          NaN        7       11   
2  19-25    Male  Student in College          NaN        7        7   
3  19-25    Male  Student in College          NaN        7        7   
4  19-25  Female  Student in College          NaN        7        7   

   travel_time  easeof_online  home_env  prod_inc  ...  fam_connect  relaxed   
0          0.5              3         3       0.0  ...          1.0     -0.5  \
1          0.5              4         2      -0.5  ...          1.0      1.0   
2          1.5              2         2       1.0  ...          0.5      0.5   
3          1.5              3         1       0.0  ...          0.0     -1.0   
4          1.5              2         2       0.0  ...          0.0      0.5   

   self_time  like_hw  dislike_hw                        prefer   
0       -0.5      100           1  Complete Physical Attendance  \
1        1.0     1111        1110  Complete Physical Attendance   
2        0.5     1100         111  Complete Physical Attendance   
3       -0.5      100        1111  Complete Physical Attendance   
4        0.0     1010        1000  Complete Physical Attendance   

   certaindays_hw Unnamed: 19 time_bp.1  travel+work  
0             Yes         NaN         7          NaN  
1              No         NaN         7          NaN  
2             Yes         NaN         7          NaN  
3             Yes         NaN         7          NaN  
4             Yes         NaN         7          NaN  

[5 rows x 22 columns]

### Brisanje nepotrebnih kolona
"Please note that all the custom columns can be ignored."
* X, net_diff - Custom Column (Unnamed: 19)
* time_bp.1  - Custom Column
* travel_new - Custom Column

In [6]:
data.drop(['Unnamed: 19', 'time_bp.1', 'travel+work'], inplace = True, axis = 1)

### Nedostajuće vrednosti

In [7]:
data.isna().sum()

age                 0
gender              0
occupation          0
line_of_work      696
time_bp             0
time_dp             0
travel_time         0
easeof_online       0
home_env            0
prod_inc            0
sleep_bal           0
new_skill           0
fam_connect         0
relaxed             0
self_time           0
like_hw             0
dislike_hw          0
prefer              0
certaindays_hw      0
dtype: int64

In [8]:
data["line_of_work"].unique()

array([nan, 'Teaching', 'Engineering', 'Management', 'APSPDCL ',
       'Architecture', 'Architect', 'Other', 'Government Employee'],
      dtype=object)

Primećujemo da kolona 'line_of_work' sadrži nedostajuće vrednosti, ona predstavlja oblast u kojoj se bave ispitanici kojima kao zanimanje piše 'Working Professional'. Nama trenutno nije bitna konkretna oblast pa ćemo ovu kolonu izbaciti.

In [9]:
data.drop(['line_of_work'], axis = 1, inplace = True)
data.isna().sum()

age               0
gender            0
occupation        0
time_bp           0
time_dp           0
travel_time       0
easeof_online     0
home_env          0
prod_inc          0
sleep_bal         0
new_skill         0
fam_connect       0
relaxed           0
self_time         0
like_hw           0
dislike_hw        0
prefer            0
certaindays_hw    0
dtype: int64

### Kodiranje kategoričkih atributa

Kategoričke atribute (koji nisu predstavljeni brojevima) potrebno je pretvoriti u numeričke vrednosti kako bi se koristili u algoritmima. 

In [10]:
from sklearn.preprocessing import LabelEncoder

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             1175 non-null   object 
 1   gender          1175 non-null   object 
 2   occupation      1175 non-null   object 
 3   time_bp         1175 non-null   int64  
 4   time_dp         1175 non-null   int64  
 5   travel_time     1175 non-null   float64
 6   easeof_online   1175 non-null   int64  
 7   home_env        1175 non-null   int64  
 8   prod_inc        1175 non-null   float64
 9   sleep_bal       1175 non-null   float64
 10  new_skill       1175 non-null   float64
 11  fam_connect     1175 non-null   float64
 12  relaxed         1175 non-null   float64
 13  self_time       1175 non-null   float64
 14  like_hw         1175 non-null   int64  
 15  dislike_hw      1175 non-null   int64  
 16  prefer          1175 non-null   object 
 17  certaindays_hw  1175 non-null   o

In [11]:
# age
print(data["age"].unique())

label_encoder = LabelEncoder()
data['age'] = label_encoder.fit_transform(data['age'])

data["age"].unique()

['19-25' '0-18' '33-40' '60+' '26-32' '40-50' '50-60']


array([1, 0, 3, 6, 2, 4, 5])

In [12]:
# gender
print(data["gender"].unique())

data['gender'] = label_encoder.fit_transform(data['gender'])
data["gender"].unique()

['Male' 'Female' 'Prefer not to say']


array([1, 0, 2])

In [13]:
# occupaation
print(data["occupation"].unique())

data['occupation'] = label_encoder.fit_transform(data['occupation'])
data["occupation"].unique()

['Student in College' 'Student in School' 'Working Professional'
 'Entrepreneur' 'Retired/Senior Citizen' 'Homemaker'
 'Currently Out of Work'
 'Medical Professional aiding efforts against COVID-19']


array([5, 6, 7, 1, 4, 2, 0, 3])

In [14]:
# prefer
print(data["prefer"].unique())

data['prefer'] = label_encoder.fit_transform(data['prefer'])
data["prefer"].unique()

['Complete Physical Attendance' 'Work/study from home']


array([0, 1])

In [15]:
# certaindays_hw
print(data["certaindays_hw"].unique())

data['certaindays_hw'] = label_encoder.fit_transform(data['certaindays_hw'])
data["certaindays_hw"].unique()

['Yes' 'No' 'Maybe']


array([2, 1, 0])

In [16]:
data.head()

age  gender  occupation  time_bp  time_dp  travel_time  easeof_online   
0    1       1           5        7        5          0.5              3  \
1    0       1           6        7       11          0.5              4   
2    1       1           5        7        7          1.5              2   
3    1       1           5        7        7          1.5              3   
4    1       0           5        7        7          1.5              2   

   home_env  prod_inc  sleep_bal  new_skill  fam_connect  relaxed  self_time   
0         3       0.0        0.0        0.5          1.0     -0.5       -0.5  \
1         2      -0.5        0.5       -1.0          1.0      1.0        1.0   
2         2       1.0        0.0        0.5          0.5      0.5        0.5   
3         1       0.0        1.0        0.5          0.0     -1.0       -0.5   
4         2       0.0        0.0        0.0          0.0      0.5        0.0   

   like_hw  dislike_hw  prefer  certaindays_hw  
0      100           1       0               2  
1     1111        1110       0               1  
2     1100         111       0               2  
3      100        1111       0               2  
4     1010        1000       0               2

### Osnovne informacije o bazi podataka

In [17]:
data.describe()

age       gender   occupation      time_bp      time_dp   
count  1175.000000  1175.000000  1175.000000  1175.000000  1175.000000  \
mean      2.552340     0.565957     4.902979     7.415319     7.971915   
std       1.679248     0.509399     2.252944     2.005385     2.657007   
min       0.000000     0.000000     0.000000     4.000000     4.000000   
25%       1.000000     0.000000     3.000000     5.000000     5.000000   
50%       2.000000     1.000000     5.000000     7.000000     9.000000   
75%       4.000000     1.000000     7.000000     9.000000     9.000000   
max       6.000000     2.000000     7.000000    12.000000    12.000000   

       travel_time  easeof_online     home_env     prod_inc    sleep_bal   
count  1175.000000    1175.000000  1175.000000  1175.000000  1175.000000  \
mean      1.027660       2.533617     2.752340     0.008936    -0.108936   
std       0.713314       1.267609     1.235799     0.615083     0.621215   
min       0.500000       1.000000     1.000000    -1.000000    -1.000000   
25%       0.500000       1.000000     2.000000    -0.500000    -0.500000   
50%       0.500000       2.000000     3.000000     0.000000     0.000000   
75%       1.500000       4.000000     4.000000     0.500000     0.500000   
max       3.000000       5.000000     5.000000     1.000000     1.000000   

         new_skill  fam_connect      relaxed    self_time      like_hw   
count  1175.000000  1175.000000  1175.000000  1175.000000  1175.000000  \
mean      0.146809     0.260426     0.035745     0.082979   734.840851   
std       0.643686     0.686825     0.626637     0.541434   468.000935   
min      -1.000000    -1.000000    -1.000000    -1.000000     1.000000   
25%      -0.500000     0.000000    -0.500000    -0.500000   100.000000   
50%       0.500000     0.500000     0.000000     0.000000  1001.000000   
75%       0.500000     1.000000     0.500000     0.500000  1100.000000   
max       1.000000     1.000000     1.000000     1.000000  1111.000000   

        dislike_hw       prefer  certaindays_hw  
count  1175.000000  1175.000000     1175.000000  
mean    651.067234     0.288511        1.229787  
std     502.319310     0.453263        0.827528  
min       1.000000     0.000000        0.000000  
25%     101.000000     0.000000        0.000000  
50%    1000.000000     0.000000        1.000000  
75%    1101.000000     1.000000        2.000000  
max    1111.000000     1.000000        2.000000

# Podela na ulazne i ciljne atribute

Ciljna promenljiva kojom ćemo meriti stepen promene načina života tokom pandemije COVID-19 ćemo konstruisati na osnovu atributa: 'prod_inc', 'sleep_bal', 'new_skill', 'fam_connect', 'relaxed' i 'self_time', pa je potrebno ove kolone i izbaciti iz ulaznog skupa podataka.

Zašto baš ovi atributi?
1. Matrica korelacije:
Na osnovu analize matrice korelacije zaključili smo da su ovi atributi imali najviše uticaja na ostale atribute koji se odnose na promenu načina života, što ukazuje na njihov potencijalni značaj.

2. Direktan uticaj na psihološko stanje:
Svaki od odabranih atributa direktno se odnosi na aspekte koji mogu značajno uticati na psihološko stanje pojedinaca. Na primer, produktivnost može biti povezano sa osećajem uspeha, opuštenost često povezujemo sa nivoom stresa, režim spavanja ima duboku vezu sa kvalitetom sna i smanjenjem umora, porodica često ima dosta veliki uticaj na nas same,...

Na osnovu  ocena koje opisuju stepen promene konkretnog aspekta, svaku osobu ćemo klasifikovati u jednu od tri kategorija:
* Negativna promena (-1): o < -0.25
* Neutralna promena  (0): -0.25 <= o <= 0.25
* Pozitivna promena  (1): o > 0.25

gde je o srednja vrednost pojedinačnih ocena.

In [18]:
# računanje srednje vrednosti ocena atributa za svakog pojedinca
data['avg_score'] = data[["prod_inc", "sleep_bal", "new_skill", "fam_connect", "relaxed", "self_time"]].mean(axis = 1)

# definisanje pragova za klasifikaciju
positive_threshold = 0.25
negative_threshold = -0.25

# kreiranje ciljne promenljive
data['lifestyle_change'] = pd.cut(data['avg_score'], 
                                  bins = [-float('inf'), negative_threshold, positive_threshold, float('inf')],
                                  labels = [-1, 0, 1])

# brisanje kolona
data.drop(['avg_score'], axis = 1, inplace = True)
data.drop(["prod_inc", "sleep_bal", "new_skill", "fam_connect", "relaxed", "self_time"], axis = 1, inplace = True)

data.head()

age  gender  occupation  time_bp  time_dp  travel_time  easeof_online   
0    1       1           5        7        5          0.5              3  \
1    0       1           6        7       11          0.5              4   
2    1       1           5        7        7          1.5              2   
3    1       1           5        7        7          1.5              3   
4    1       0           5        7        7          1.5              2   

   home_env  like_hw  dislike_hw  prefer  certaindays_hw lifestyle_change  
0         3      100           1       0               2                0  
1         2     1111        1110       0               1                1  
2         2     1100         111       0               2                1  
3         1      100        1111       0               2                0  
4         2     1010        1000       0               2                0

### Balansiranost klasa

In [19]:
data.lifestyle_change.value_counts()

lifestyle_change
0     428
1     421
-1    326
Name: count, dtype: int64

In [20]:
fig, axs = plt.subplots(1, 2, figsize=(10, 5))

# kreiranje countplot sa sortiranim kategorijama 
sns.countplot(x = data["lifestyle_change"], order = sorted(set(data["lifestyle_change"])), ax = axs[0], palette = 'pastel')
axs[0].set_xlabel('Categories')
axs[0].set_ylabel('Count')

# kreiranje pie chart-a 
color = [sns.color_palette('pastel')[1], sns.color_palette('pastel')[2], sns.color_palette('pastel')[0]]
gender_map = data['lifestyle_change'].value_counts()
axs[1].pie(gender_map, labels = gender_map.index, autopct = '%.1f%%', colors = color, startangle = 140)

fig.suptitle("Lifestyle change")
plt.show()

S obzirom na ove vrednosti, možemo utvrditi da podaci nisu savršeno balansirani, ali razlike nisu drastične.
Za sada nećemo primeniti nikakve tehnike balansiranja. Ukoliko primetimo da neravnoteža negativno utiče na performanse modela, tada ćemo primeniti neku tehniku za balansiranje klasa.

### Podela

In [21]:
y = data['lifestyle_change']
X = data.drop('lifestyle_change', axis=1)

In [22]:
print(X.shape)
X.head()

(1175, 12)


age  gender  occupation  time_bp  time_dp  travel_time  easeof_online   
0    1       1           5        7        5          0.5              3  \
1    0       1           6        7       11          0.5              4   
2    1       1           5        7        7          1.5              2   
3    1       1           5        7        7          1.5              3   
4    1       0           5        7        7          1.5              2   

   home_env  like_hw  dislike_hw  prefer  certaindays_hw  
0         3      100           1       0               2  
1         2     1111        1110       0               1  
2         2     1100         111       0               2  
3         1      100        1111       0               2  
4         2     1010        1000       0               2

In [23]:
print(y.shape)
y.head()

(1175,)


0    0
1    1
2    1
3    0
4    0
Name: lifestyle_change, dtype: category
Categories (3, int64): [-1 < 0 < 1]

## Podela podataka na trening i test skup

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

((940, 12), (235, 12), (940,), (235,))

### Standardizacija podataka

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
scaler = StandardScaler()

scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train = pd.DataFrame(data = X_train_scaled, columns = X_train.columns)
X_test = pd.DataFrame(data = X_test_scaled, columns = X_test.columns)

In [28]:
X_train.head()

age    gender  occupation   time_bp   time_dp  travel_time   
0 -0.947570  0.861299    0.036684 -1.198908 -1.501145    -0.740219  \
1 -0.356125  0.861299    0.920868  0.819853  1.151966    -0.740219   
2 -0.947570  0.861299    0.036684  0.819853 -1.122129     2.114371   
3  1.418209 -1.103801   -1.289592 -1.198908  1.530982    -0.740219   
4 -0.947570  0.861299    0.036684 -0.189527 -1.122129    -0.740219   

   easeof_online  home_env   like_hw  dislike_hw    prefer  certaindays_hw  
0      -1.210951  0.195500  0.825107    0.704951  1.551063        0.932885  
1      -1.210951  1.821780  0.827224    0.925670 -0.644719        0.932885  
2      -0.425921  1.008640  0.803932    0.925670 -0.644719        0.932885  
3      -1.210951 -0.617641 -1.292435   -1.281525  1.551063       -1.472909  
4      -0.425921 -1.430781  0.592177    0.704951  1.551063        0.932885

In [29]:
X_train.describe()

age        gender    occupation       time_bp       time_dp   
count  9.400000e+02  9.400000e+02  9.400000e+02  9.400000e+02  9.400000e+02  \
mean  -1.039358e-16 -1.011012e-16  7.558965e-18 -1.795254e-16  7.558965e-18   
std    1.000532e+00  1.000532e+00  1.000532e+00  1.000532e+00  1.000532e+00   
min   -1.539015e+00 -1.103801e+00 -2.173776e+00 -1.703598e+00 -1.501145e+00   
25%   -9.475702e-01 -1.103801e+00 -8.474999e-01 -1.198908e+00 -1.122129e+00   
50%   -3.561253e-01  8.612992e-01  3.668423e-02 -1.895273e-01  3.939346e-01   
75%    8.267644e-01  8.612992e-01  9.208684e-01  8.198534e-01  3.939346e-01   
max    2.009654e+00  2.826399e+00  9.208684e-01  2.333924e+00  1.530982e+00   

        travel_time  easeof_online      home_env       like_hw    dislike_hw   
count  9.400000e+02   9.400000e+02  9.400000e+02  9.400000e+02  9.400000e+02  \
mean   7.511722e-17   1.587383e-16 -3.023586e-17  1.606280e-17  4.535379e-17   
std    1.000532e+00   1.000532e+00  1.000532e+00  1.000532e+00  1.000532e+00   
min   -7.402195e-01  -1.210951e+00 -1.430781e+00 -1.523247e+00 -1.281525e+00   
25%   -7.402195e-01  -1.210951e+00 -6.176406e-01 -1.313610e+00 -1.082679e+00   
50%   -7.402195e-01  -4.259209e-01  1.954997e-01  5.921773e-01  7.049509e-01   
75%    6.870755e-01   1.144140e+00  1.008640e+00  8.039315e-01  9.057858e-01   
max    2.828018e+00   1.929171e+00  1.821780e+00  8.272245e-01  9.256704e-01   

             prefer  certaindays_hw  
count  9.400000e+02    9.400000e+02  
mean   3.212560e-17    1.511793e-17  
std    1.000532e+00    1.000532e+00  
min   -6.447190e-01   -1.472909e+00  
25%   -6.447190e-01   -1.472909e+00  
50%   -6.447190e-01   -2.700120e-01  
75%    1.551063e+00    9.328851e-01  
max    1.551063e+00    9.328851e-01

Podatke za klasterovanje nećemo sada standardizovati, već ćemo ih standardizovati pre same upotrebe nekog algoritma za klasterovanje jer će nam ovi originalni podaci biti značajni za razumevanje interpretacije klastera.

## Čuvanje sređenih baza podataka

In [30]:
from joblib import dump

In [31]:
dump((X_train, X_test, y_train, y_test), 'classification_data.joblib')

['classification_data.joblib']

In [32]:
dump((X, y), 'clustering_data.joblib')

['clustering_data.joblib']

In [33]:
# računanje srednje vrednosti ocena atributa za svakog pojedinca
datac['avg_score'] = datac[["prod_inc", "sleep_bal", "new_skill", "fam_connect", "relaxed", "self_time"]].mean(axis=1)

# definisanje pragova za klasifikaciju
positive_threshold = 0.25
negative_threshold = -0.25

# kreiranje ciljne promenljive
datac['lifestyle_change'] = pd.cut(datac['avg_score'], 
                                  bins = [-float('inf'), negative_threshold, positive_threshold, float('inf')],
                                  labels = [-1, 0, 1])

time_change = datac['time_dp'] - datac['time_bp']
datac['time_change'] = time_change
datac.drop(['time_dp', 'time_bp'], inplace = True, axis = 1)


datac.to_csv('psyco_lifestyle_change.csv', index = False)